### ISSUE TITLE
Can't craft Torch variants + Internal Exception on server

### ISSUE THREAD

**Issue by TheMasterBlaster** [pnk2u/More-Torch-Variants#1]
I can't seem to craft any of the Torch variants while on a server but I can in Singleplayer. When trying to give myself a Torch variant in creative mod, the client disconnects with the reason 

"Internal Exception: io.netty.handler.codec.DecoderException: Failed to decode packet 'serverbound/minecraft:set_creative_mode_slot"

Minecraft version - 1.21
Fabric API - 0.103.0
Quad - 1.3.0-beta.5 & 1.2.7
All of your More mods updated to latest for 1.21

**Comment by TheMasterBlaster** [comment]
I keep getting a server-side crash [with quad 1.3.0-beta.5](https://github.com/user-attachments/files/16936335/quad.1.3.0-beta.5.txt) when generating new chunks

**Comment by pnk2u** [comment]
Sorry about this but good news, very small thing, I'll fix it right away in version 1.0.2.
And thanks again for reporting, I appreciate it a lot. (:
The server-side crash of Quad is directly related (same issue) and as such will be fixed, too.

Btw: Quad 1.3.0's new feature is block replacement during generation meaning that any village (and other structures, too) can have fitting variants for any mod, e.g. a Savanna village having only Acacia Torches, Acacia Barrels, Acacia Smokers etc. instead of the vanilla blocks. Mods that currently have this featured implemented are More Barrel Variants, More Fletching Tables, More Grindstone Variants (was bugged, is fixed in 1.0.4) and More Torch Variants.
So one thing I would like to know while we're at it: Which of my mods are you using? I can then add the functionality to those ones first. (:

Edit: 1.0.2 is out now. (:

**Comment by TheMasterBlaster** [comment]
More Torch Variants is working correctly now. Thank ya!
I have most if not all of your more variants mods actually. I love the extra esthetic your mods add the Minecraft.

**Comment by pnk2u** [comment]
Quad 1.3.0's block replacement has been added to all my mods where it is applicable.
I just kept this issue open because I was meaning to come back to you on this one but it must've slipped my mind. Thanks for enjoying my mods. (:
